### ISSUE TITLE
Impossible to connect with gestion@lokavaluto.fr account

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/lokavaluto-mobile-application#4]
Phone: oneplus two (rom lineage os 17) android 10

I open the app, ltry to log in with gestion@lokavaluto.fr account and obtain the following error:

'could not obtain token: access denied'

PS: it's working with alain terrieur

Update: now it's not working with alain terrieur (same error) but working with gestion@lokavaluto.fr

**Comment by farfromrefug** [comment]
@MatSarr  that s seem to be a server error. Especially if it is random. It would be very useful to have access to server request logs

**Comment by stephansainleger** [comment]
Works on my side. @MatSarr do you still reproduce the issue?

**Comment by MatSarr** [comment]
I'm not able to reproduce. I close the issue.
